#----------------------------
# Server configuration
#----------------------------
server:
  port:8081
spring:
  main:
    lazy-initialization: on
    banner-mode: "off"
    #Error
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_trace_param
      include-exception: false
    # Database
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/hexagonal/database;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
      username: sa
      password: password
    jpa:
      hibernate:
      # When you launch the application for the first time - switch "none" at "create"
      #Hibernate ddl auto (create, create-drop, update)
      ddl-auto: update
      show-sql: true
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      open-in-view: false
      generate-ddl: false
      defer-datasource-initialization: false
    #h2:
     # console:
     # enabled: true
     # path: /h2-console

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
