#----------------------------
# Server configuration
#----------------------------
server:
  port:8081
spring:
  main:
    banner-mode: "off"
    #Error
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_trace_param
      include-exception: false
    # Database
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db
      username: sa
      password: password
    jpa:
      hibernate:
        # When you launch the application for the first time - switch "none" at "create"
        #Hibernate ddl auto (create, create-drop, update)
        ddl-auto: create-drop
      show-sql: true
      database: h2
      database-platform: org.hibernate.dialect.H2Dialect
      open-in-view: false
      generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: debug
    org.hibernate: debug
